import type { Metadata } from "next";
import "./globals.css";
import { Slide, ToastContainer } from "react-toastify";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"

      
    >
      <body >
        
        <ToastContainer
position="top-center"
autoClose={2500}
hideProgressBar
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition={Slide}
/>
        
        {children}</body>
    </html>
  );
}
